(function(){
Object.keys(weeks).forEach(k=>delete weeks[k]);
Object.assign(weeks,window.ACTIVITY_PERIODS||{});
const selector=document.querySelector('#week');
selector.innerHTML='<optgroup label="按月查看">'+Array.from({length:7},(_,i)=>{const k='m'+(i+1),w=weeks[k];return '<option value="'+k+'">'+w.label+' · '+w.range+'</option>'}).join('')+'</optgroup><optgroup label="按周查看">'+Array.from({length:31},(_,i)=>{const k='w'+(i+1),w=weeks[k];return '<option value="'+k+'">'+w.label+' · '+w.range+'</option>'}).join('')+'</optgroup>';
selector.value='m7';
const fmtPct=n=>n==null?'—':Number(n).toFixed(1)+'%';
renderKpis=function(w){const m=w.metrics,c=w.comparison||{},cmp=c.salesPct==null?'本期数据':('环比 '+(c.salesPct>=0?'+':'')+c.salesPct.toFixed(1)+'%');const cards=[
 kcard('活动销售额',money(m.sales),cmp,c.salesPct>=0?'good':c.salesPct==null?'':'warn'),
 kcard('活动费用',money(m.fees),'本期活动投入',m.feeRatio<=8?'good':'warn'),
 kcard('综合费比',m.feeRatio.toFixed(2)+'%',m.feeRatio<=8?'控制在8%以内':'高于8%观察线',m.feeRatio<=8?'good':'warn'),
 kcard('活动场次',m.events,w.isMonth?'月度执行场次':'周度执行场次'),
 kcard('活动人效',m.humanEff!=null?money(m.humanEff)+'/人天':'—','标准：¥1,000/人天',m.humanEff>=1000?'good':'warn'),
 kcard('人效达标率',fmtPct(m.humanHitRate),(m.hitCount||0)+'场达标 / '+(m.validCount||0)+'场有效',m.humanHitRate>=50?'good':'warn'),
 kcard('促销人天',num(m.personDays),'销售额 ÷ 促销人天 = 人效'),
 kcard('巡店数据','待接入','活动数据已更新','warn')];
 document.querySelector('#kpis').innerHTML=cards.join('');
};
drawTrend=function(){const w=weeks[selector.value],c=document.querySelector('#trendCanvas'),dpr=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*dpr;c.height=r.height*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);const W=r.width,H=r.height,p=45,data=(w.trend||[]).slice(-6);x.clearRect(0,0,W,H);if(!data.length)return;const max=Math.max(...data.map(v=>v.sales),1)*1.18,rateMax=Math.max(12,...data.map(v=>v.feeRatio||0)),step=(W-2*p)/data.length,barW=Math.min(62,step*.5);x.strokeStyle='#dbc9a7';x.beginPath();x.moveTo(p,15);x.lineTo(p,H-p);x.lineTo(W-20,H-p);x.stroke();const pts=[];data.forEach((v,i)=>{const bx=p+step*i+(step-barW)/2,bh=v.sales/max*(H-80);x.fillStyle='#ffcc00';x.fillRect(bx,H-p-bh,barW,bh);x.fillStyle='#632c16';x.font='11px HuakangW7';x.fillText(v.week,bx+4,H-p+20);x.font='11px HuakangW9';x.fillText('¥'+(v.sales/10000).toFixed(1)+'万',bx,H-p-bh-8);pts.push([bx+barW/2,H-p-(v.feeRatio||0)/rateMax*(H-80),v.feeRatio||0])});x.strokeStyle='#d93924';x.lineWidth=3;x.beginPath();pts.forEach((q,i)=>i?x.lineTo(q[0],q[1]):x.moveTo(q[0],q[1]));x.stroke();pts.forEach(q=>{x.fillStyle='#d93924';x.beginPath();x.arc(q[0],q[1],5,0,Math.PI*2);x.fill();x.font='11px HuakangW7';x.fillText(q[2].toFixed(1)+'%',q[0]+7,q[1]-5)});
};
drawQuad=function(w){const c=document.querySelector('#quadCanvas'),ctx=c.getContext('2d'),r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle='#fff8e3';ctx.fillRect(0,0,r.width,r.height);ctx.fillStyle='#632c16';ctx.font='900 18px HuakangW9';ctx.fillText('巡店数据待接入',45,85);ctx.font='14px HuakangW7';ctx.fillText('收到巡店台账后，将自动恢复“活动人效 × 巡店达成率”城市四象限。',45,120);ctx.fillText('当前活动销售、费用、费比和人效已按所选月份/周次更新。',45,148)};
renderEfficiency=function(w){const el=document.querySelector('#effContent'),levels=w.levels||[],max=Math.max(...levels.map(x=>x.humanEff||0),1);const bars=levels.map((x,i)=>'<div class="barrow"><b>'+x.level+'</b><div class="track"><div class="fill '+(i?'b':'')+'" style="width:'+((x.humanEff||0)/max*100)+'%"></div></div><span>'+money(x.humanEff)+'/人天</span></div>').join('');const rows=(w.low||[]).map(x=>'<tr><td>'+x[0]+'</td><td>'+x[1]+'</td><td>'+money(x[2])+'</td><td><span class="pill bad">未达标</span></td></tr>').join('');const cards=levels.map(x=>kcard(x.level+'人效',money(x.humanEff),x.events+'场 · 达标率'+fmtPct(x.humanHitRate),x.humanEff>=1000?'good':'warn')).join('');el.innerHTML='<div class="grid kpis">'+kcard('整体人效',money(w.metrics.humanEff),'标准 ¥1,000/人天',w.metrics.humanEff>=1000?'good':'warn')+kcard('达标率',fmtPct(w.metrics.humanHitRate),(w.metrics.hitCount||0)+'场达标 / '+(w.metrics.validCount||0)+'场有效',w.metrics.humanHitRate>=50?'good':'warn')+kcard('促销人天',num(w.metrics.personDays),'活动资源投入')+cards+'</div><div class="grid two" style="margin-top:16px"><div class="card"><div class="chart-title">不同活动类型人效</div><div class="bars">'+bars+'</div><p class="fine">人效 = 销售额 ÷ 促销人员天数；目标为1,000元/人天。</p></div><div class="card"><div class="chart-title">低效活动优先复盘</div><div class="table-wrap"><table><thead><tr><th>城市</th><th>门店/活动</th><th>人效</th><th>状态</th></tr></thead><tbody>'+rows+'</tbody></table></div></div></div>'};
renderPatrol=function(){document.querySelector('#patrolContent').innerHTML='<div class="card note"><b>巡店数据待接入</b><p>本次仅替换活动数据。待你提供1—7月巡店台账后，这里会恢复城市经理与执行督导目标达成、门店覆盖和巡店质量评分。</p></div>'};
renderCities=function(w){document.querySelector('#cityTable').innerHTML=(w.cities||[]).map(x=>'<tr><td><b>'+x.city+'</b></td><td>'+x.events+'</td><td>'+money(x.sales)+'</td><td>'+money(x.fees)+'</td><td>'+x.feeRatio.toFixed(2)+'%</td><td>'+(x.humanEff!=null?money(x.humanEff)+'/人天':'—')+'</td><td>'+fmtPct(x.humanHitRate)+'</td></tr>').join('')};
render=function(){const w=weeks[selector.value]||weeks.m7;document.querySelector('#sideWeek').textContent='当前：2026年'+w.label;document.querySelector('#trend .title').textContent=w.isMonth?w.label+'周度经营趋势':w.label+'及近5周经营趋势';renderKpis(w);renderEfficiency(w);renderPatrol(w);renderCities(w);document.querySelector('#archiveContent').innerHTML='<div class="chart-title">'+w.label+'（'+w.range+'）</div><p>'+w.archive+'</p><p class="fine">数据来源：皇家小虎浙江省区1—7月活动台账；共631条去重活动。周次按周六至周五归属，W1为2025/12/27—2026/1/2。</p>';document.querySelector('#trendInsight').innerHTML='<b>本期关键判断</b><p>'+w.insight+'</p>';document.querySelector('#quadNote').textContent='巡店数据待接入；活动维度已按'+w.label+'更新。';requestAnimationFrame(()=>{drawTrend();drawQuad(w)})};
selector.addEventListener('change',render);
addEventListener('resize',render);
render();
})();
