
window.JULY_DATA={
  "quality": {
    "activityRows": 93,
    "activityUnique": 91,
    "activityDuplicates": 2,
    "visitRows": 988,
    "visitUniqueStores": 581
  },
  "total": {
    "events": 91,
    "sales": 242667.06,
    "fees": 17697.76,
    "feeRatio": 7.29,
    "personDays": 203,
    "humanEff": 1195.4,
    "hitRate": 43,
    "hitCount": 37,
    "validCount": 86,
    "visits": 988,
    "uniqueStores": 581
  },
  "weekly": [
    {
      "events": 5,
      "sales": 19487.5,
      "fees": 772.48,
      "feeRatio": 3.96,
      "personDays": 9,
      "humanEff": 2165.28,
      "hitRate": 50,
      "hitCount": 2,
      "validCount": 4,
      "week": "W27(7/1-7/3)",
      "visits": 146
    },
    {
      "events": 20,
      "sales": 40353.38,
      "fees": 3768.5,
      "feeRatio": 9.34,
      "personDays": 49,
      "humanEff": 823.54,
      "hitRate": 25,
      "hitCount": 5,
      "validCount": 20,
      "week": "W28(7/4-7/10)",
      "visits": 312
    },
    {
      "events": 19,
      "sales": 74807.49,
      "fees": 5278.58,
      "feeRatio": 7.06,
      "personDays": 49,
      "humanEff": 1526.68,
      "hitRate": 52.6,
      "hitCount": 10,
      "validCount": 19,
      "week": "W29(7/11-7/17)",
      "visits": 170
    },
    {
      "events": 31,
      "sales": 81123.52,
      "fees": 4708.31,
      "feeRatio": 5.8,
      "personDays": 69,
      "humanEff": 1175.7,
      "hitRate": 46.4,
      "hitCount": 13,
      "validCount": 28,
      "week": "W30(7/18-7/24)",
      "visits": 208
    },
    {
      "events": 16,
      "sales": 26895.17,
      "fees": 3169.89,
      "feeRatio": 11.79,
      "personDays": 27,
      "humanEff": 996.12,
      "hitRate": 46.7,
      "hitCount": 7,
      "validCount": 15,
      "week": "W31(7/25-7/31)",
      "visits": 152
    }
  ],
  "levels": [
    {
      "events": 60,
      "sales": 123069.96,
      "fees": 11779.02,
      "feeRatio": 9.57,
      "personDays": 123,
      "humanEff": 1000.57,
      "hitRate": 47.4,
      "hitCount": 27,
      "validCount": 57,
      "level": "小型活动"
    },
    {
      "events": 13,
      "sales": 91867.31,
      "fees": 5617.63,
      "feeRatio": 6.11,
      "personDays": 46,
      "humanEff": 1997.12,
      "hitRate": 83.3,
      "hitCount": 10,
      "validCount": 12,
      "level": "中型活动"
    },
    {
      "events": 18,
      "sales": 27729.79,
      "fees": 301.11,
      "feeRatio": 1.09,
      "personDays": 34,
      "humanEff": 815.58,
      "hitRate": 0,
      "hitCount": 0,
      "validCount": 17,
      "level": "CP活动"
    }
  ],
  "cities": [
    {
      "events": 7,
      "sales": 48098.8,
      "fees": 3011.9,
      "feeRatio": 6.26,
      "personDays": 19,
      "humanEff": 2531.52,
      "hitRate": 66.7,
      "hitCount": 4,
      "validCount": 6,
      "city": "金华市",
      "visits": 139
    },
    {
      "events": 25,
      "sales": 42802.32,
      "fees": 4450.73,
      "feeRatio": 10.4,
      "personDays": 41,
      "humanEff": 1043.96,
      "hitRate": 45.8,
      "hitCount": 11,
      "validCount": 24,
      "city": "上海市",
      "visits": 123
    },
    {
      "events": 10,
      "sales": 34154.89,
      "fees": 4009.01,
      "feeRatio": 11.74,
      "personDays": 21,
      "humanEff": 1626.42,
      "hitRate": 80,
      "hitCount": 8,
      "validCount": 10,
      "city": "温州市",
      "visits": 144
    },
    {
      "events": 2,
      "sales": 21761.57,
      "fees": 1840,
      "feeRatio": 8.46,
      "personDays": 27,
      "humanEff": 805.98,
      "hitRate": 0,
      "hitCount": 0,
      "validCount": 2,
      "city": "绍兴市",
      "visits": 82
    },
    {
      "events": 8,
      "sales": 20070.1,
      "fees": 2306.3,
      "feeRatio": 11.49,
      "personDays": 21,
      "humanEff": 955.72,
      "hitRate": 37.5,
      "hitCount": 3,
      "validCount": 8,
      "city": "衢州市",
      "visits": 79
    },
    {
      "events": 14,
      "sales": 19061.5,
      "fees": 601.2,
      "feeRatio": 3.15,
      "personDays": 28,
      "humanEff": 680.77,
      "hitRate": 21.4,
      "hitCount": 3,
      "validCount": 14,
      "city": "苏州市",
      "visits": 0
    },
    {
      "events": 3,
      "sales": 16319.61,
      "fees": 270.2,
      "feeRatio": 1.66,
      "personDays": 8,
      "humanEff": 2039.95,
      "hitRate": 100,
      "hitCount": 3,
      "validCount": 3,
      "city": "台州市",
      "visits": 41
    },
    {
      "events": 3,
      "sales": 14098.28,
      "fees": 612.92,
      "feeRatio": 4.35,
      "personDays": 5,
      "humanEff": 2819.66,
      "hitRate": 66.7,
      "hitCount": 2,
      "validCount": 3,
      "city": "嘉兴市",
      "visits": 77
    },
    {
      "events": 4,
      "sales": 7718.28,
      "fees": 480.3,
      "feeRatio": 6.22,
      "personDays": 9,
      "humanEff": 857.59,
      "hitRate": 50,
      "hitCount": 2,
      "validCount": 4,
      "city": "宁波市",
      "visits": 65
    },
    {
      "events": 7,
      "sales": 6686.67,
      "fees": 75.48,
      "feeRatio": 1.13,
      "personDays": 8,
      "humanEff": 835.83,
      "hitRate": 0,
      "hitCount": 0,
      "validCount": 4,
      "city": "杭州市",
      "visits": 135
    },
    {
      "events": 4,
      "sales": 4911.01,
      "fees": 0.5,
      "feeRatio": 0.01,
      "personDays": 8,
      "humanEff": 613.88,
      "hitRate": 0,
      "hitCount": 0,
      "validCount": 4,
      "city": "宿迁市",
      "visits": 0
    },
    {
      "events": 2,
      "sales": 4667.3,
      "fees": 5.11,
      "feeRatio": 0.11,
      "personDays": 4,
      "humanEff": 1166.82,
      "hitRate": 50,
      "hitCount": 1,
      "validCount": 2,
      "city": "湖州市",
      "visits": 36
    },
    {
      "events": 1,
      "sales": 1284.63,
      "fees": 0.1,
      "feeRatio": 0.01,
      "personDays": 2,
      "humanEff": 642.32,
      "hitRate": 0,
      "hitCount": 0,
      "validCount": 1,
      "city": "南京市",
      "visits": 0
    },
    {
      "events": 1,
      "sales": 1032.1,
      "fees": 34.01,
      "feeRatio": 3.3,
      "personDays": 2,
      "humanEff": 516.05,
      "hitRate": 0,
      "hitCount": 0,
      "validCount": 1,
      "city": "丽水市",
      "visits": 59
    }
  ],
  "people": [
    {
      "name": "甘遂",
      "role": "执行督导",
      "city": "温州市",
      "visits": 35,
      "unique": 35,
      "target": 30,
      "achievement": 116.7,
      "avgSku": 10.9,
      "avgFreezer": 1.4,
      "score": 100,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "明非",
      "role": "执行督导",
      "city": "金华市",
      "visits": 35,
      "unique": 34,
      "target": 30,
      "achievement": 116.7,
      "avgSku": 12.5,
      "avgFreezer": 1,
      "score": 99.6,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "文棠",
      "role": "执行督导",
      "city": "杭州市",
      "visits": 34,
      "unique": 32,
      "target": 30,
      "achievement": 113.3,
      "avgSku": 5.9,
      "avgFreezer": 1.8,
      "score": 99.1,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "飞鹏",
      "role": "城市经理",
      "city": "温州市",
      "visits": 69,
      "unique": 62,
      "target": 50,
      "achievement": 138,
      "avgSku": 9.6,
      "avgFreezer": 15.7,
      "score": 98.5,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "程程",
      "role": "执行督导",
      "city": "金华市",
      "visits": 29,
      "unique": 29,
      "target": 30,
      "achievement": 96.7,
      "avgSku": 11.9,
      "avgFreezer": 1.1,
      "score": 97.6,
      "compQuality": 14,
      "impQuality": 15
    },
    {
      "name": "黑泽",
      "role": "执行督导",
      "city": "金华市",
      "visits": 38,
      "unique": 32,
      "target": 30,
      "achievement": 126.7,
      "avgSku": 12.1,
      "avgFreezer": 1.4,
      "score": 97.6,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "三分",
      "role": "执行督导",
      "city": "嘉兴市",
      "visits": 33,
      "unique": 31,
      "target": 30,
      "achievement": 110,
      "avgSku": 13.7,
      "avgFreezer": 1.3,
      "score": 97.3,
      "compQuality": 15,
      "impQuality": 13.2
    },
    {
      "name": "柳贯一",
      "role": "执行督导",
      "city": "宁波市",
      "visits": 30,
      "unique": 30,
      "target": 30,
      "achievement": 100,
      "avgSku": 8.2,
      "avgFreezer": 1,
      "score": 95.5,
      "compQuality": 15,
      "impQuality": 10.5
    },
    {
      "name": "代代",
      "role": "执行督导",
      "city": "丽水市",
      "visits": 28,
      "unique": 24,
      "target": 30,
      "achievement": 93.3,
      "avgSku": 8,
      "avgFreezer": 1.4,
      "score": 95.2,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "向清",
      "role": "执行督导",
      "city": "衢州市",
      "visits": 29,
      "unique": 22,
      "target": 30,
      "achievement": 96.7,
      "avgSku": 11.9,
      "avgFreezer": 1.4,
      "score": 95,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "平安",
      "role": "城市经理",
      "city": "上海市",
      "visits": 50,
      "unique": 30,
      "target": 50,
      "achievement": 100,
      "avgSku": 9.5,
      "avgFreezer": 1.2,
      "score": 94,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "蘑菇",
      "role": "执行督导",
      "city": "杭州市",
      "visits": 32,
      "unique": 28,
      "target": 30,
      "achievement": 106.7,
      "avgSku": 6.2,
      "avgFreezer": 1.4,
      "score": 93.4,
      "compQuality": 15,
      "impQuality": 10.3
    },
    {
      "name": "砚山",
      "role": "城市经理",
      "city": "衢州市",
      "visits": 50,
      "unique": 32,
      "target": 50,
      "achievement": 100,
      "avgSku": 12.9,
      "avgFreezer": 1.5,
      "score": 92.5,
      "compQuality": 15,
      "impQuality": 12.9
    },
    {
      "name": "君祺",
      "role": "城市经理",
      "city": "金华市",
      "visits": 42,
      "unique": 38,
      "target": 50,
      "achievement": 84,
      "avgSku": 10.5,
      "avgFreezer": 1.4,
      "score": 92.2,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "卡农",
      "role": "执行督导",
      "city": "台州市",
      "visits": 23,
      "unique": 22,
      "target": 30,
      "achievement": 76.7,
      "avgSku": 7,
      "avgFreezer": 1.3,
      "score": 90,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "靖然",
      "role": "执行督导",
      "city": "温州市",
      "visits": 26,
      "unique": 16,
      "target": 30,
      "achievement": 86.7,
      "avgSku": 6.6,
      "avgFreezer": 1,
      "score": 88.9,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "俊杰",
      "role": "城市经理",
      "city": "嘉兴市",
      "visits": 41,
      "unique": 27,
      "target": 50,
      "achievement": 82,
      "avgSku": 13.7,
      "avgFreezer": 1,
      "score": 87.7,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "满云",
      "role": "执行督导",
      "city": "上海市",
      "visits": 22,
      "unique": 19,
      "target": 30,
      "achievement": 73.3,
      "avgSku": 8.5,
      "avgFreezer": 1.4,
      "score": 87.3,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "星翰",
      "role": "城市经理",
      "city": "上海市",
      "visits": 38,
      "unique": 29,
      "target": 50,
      "achievement": 76,
      "avgSku": 7.4,
      "avgFreezer": 1,
      "score": 86.8,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "天明",
      "role": "城市经理",
      "city": "宁波市",
      "visits": 35,
      "unique": 31,
      "target": 50,
      "achievement": 70,
      "avgSku": 13.4,
      "avgFreezer": 1,
      "score": 84.6,
      "compQuality": 14.1,
      "impQuality": 14.1
    },
    {
      "name": "江寻",
      "role": "执行督导",
      "city": "温州市",
      "visits": 20,
      "unique": 19,
      "target": 30,
      "achievement": 66.7,
      "avgSku": 9.7,
      "avgFreezer": 1.3,
      "score": 82.2,
      "compQuality": 15,
      "impQuality": 11.2
    },
    {
      "name": "王小白",
      "role": "执行督导",
      "city": "绍兴市",
      "visits": 32,
      "unique": 28,
      "target": 30,
      "achievement": 106.7,
      "avgSku": 8.4,
      "avgFreezer": 1.3,
      "score": 79.4,
      "compQuality": 7.5,
      "impQuality": 3.8
    },
    {
      "name": "烟雨",
      "role": "城市经理",
      "city": "湖州市",
      "visits": 33,
      "unique": 15,
      "target": 50,
      "achievement": 66,
      "avgSku": 13,
      "avgFreezer": 2,
      "score": 78.2,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "凌诚",
      "role": "城市经理",
      "city": "杭州市",
      "visits": 43,
      "unique": 30,
      "target": 50,
      "achievement": 86,
      "avgSku": 8.1,
      "avgFreezer": 1.8,
      "score": 75.6,
      "compQuality": 15,
      "impQuality": 0.7
    },
    {
      "name": "拾玖",
      "role": "城市经理",
      "city": "杭州市",
      "visits": 27,
      "unique": 23,
      "target": 50,
      "achievement": 54,
      "avgSku": 5.4,
      "avgFreezer": 1,
      "score": 74.9,
      "compQuality": 14.4,
      "impQuality": 11.1
    },
    {
      "name": "坚石",
      "role": "执行督导",
      "city": "上海市",
      "visits": 12,
      "unique": 9,
      "target": 30,
      "achievement": 40,
      "avgSku": 12.1,
      "avgFreezer": 1,
      "score": 72.2,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "栋凯",
      "role": "执行督导",
      "city": "绍兴市",
      "visits": 50,
      "unique": 20,
      "target": 30,
      "achievement": 166.7,
      "avgSku": 7,
      "avgFreezer": 1.1,
      "score": 69.7,
      "compQuality": 8.1,
      "impQuality": 0.6
    },
    {
      "name": "杰果",
      "role": "城市经理",
      "city": "丽水市",
      "visits": 33,
      "unique": 24,
      "target": 50,
      "achievement": 66,
      "avgSku": 10,
      "avgFreezer": 1.5,
      "score": 69.6,
      "compQuality": 8.6,
      "impQuality": 8.6
    },
    {
      "name": "荆言",
      "role": "执行督导",
      "city": "台州市",
      "visits": 8,
      "unique": 8,
      "target": 30,
      "achievement": 26.7,
      "avgSku": 5.9,
      "avgFreezer": 1.4,
      "score": 68.8,
      "compQuality": 13.1,
      "impQuality": 15
    },
    {
      "name": "启源",
      "role": "执行督导",
      "city": "杭州市",
      "visits": 5,
      "unique": 5,
      "target": 30,
      "achievement": 16.7,
      "avgSku": 6,
      "avgFreezer": 1.6,
      "score": 66.7,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "丁日",
      "role": "执行督导",
      "city": "湖州市",
      "visits": 3,
      "unique": 3,
      "target": 30,
      "achievement": 10,
      "avgSku": 16,
      "avgFreezer": 1,
      "score": 64,
      "compQuality": 15,
      "impQuality": 15
    },
    {
      "name": "槿川",
      "role": "执行督导",
      "city": "上海市",
      "visits": 3,
      "unique": 3,
      "target": 30,
      "achievement": 10,
      "avgSku": 12.3,
      "avgFreezer": 1.7,
      "score": 64,
      "compQuality": 15,
      "impQuality": 15
    }
  ]
};


